# CSV file validation

In [2]:
import pandas as pd
data=pd.read_csv(r"C:\Users\mouni\Desktop\bank1.csv")

In [3]:
data.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may    1042.0         1   -1.0         0  unknown     yes  
1    5   may    1467.0         1   -1.0         0  unknown     yes  
2    5   may    1389.0         1   -1.0         0  unknown     yes  
3    5   may     579.0         1   -1.0         0  unknown     yes  
4    5   may     673.0         2   -1.0         0  unknown     yes

In [4]:
data.shape

(608, 17)

# checking for null values

In [5]:
data.isnull().any()

age          False
job           True
marital      False
education     True
default      False
balance      False
housing      False
loan         False
contact       True
day          False
month        False
duration      True
campaign     False
pdays         True
previous     False
poutcome      True
deposit      False
dtype: bool

In [6]:
l=list(data.isnull().any())

In [7]:
l

[False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False]

In [8]:
d=list(data)

In [9]:
d

['age',
 'job',
 'marital',
 'education',
 'default',
 'balance',
 'housing',
 'loan',
 'contact',
 'day',
 'month',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'deposit']

# Filling Null values

In [10]:
for i in range(len(l)):
    if(l[i]):
        data[d[i]].fillna(data[d[i]].mode()[0],inplace = True) 

In [11]:
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

# identifying the datatype

In [12]:
dl=[]
for j in range(len(l)):
    dl.append((type(data[d[j]][1])))

In [13]:
dl

[numpy.int64,
 str,
 str,
 str,
 str,
 numpy.int64,
 str,
 str,
 str,
 numpy.int64,
 str,
 numpy.float64,
 numpy.int64,
 numpy.float64,
 numpy.int64,
 str,
 str]

In [14]:
dt={d[k]:dl[k] for k in range(0,len(dl))}   

In [15]:
dt

{'age': numpy.int64,
 'job': str,
 'marital': str,
 'education': str,
 'default': str,
 'balance': numpy.int64,
 'housing': str,
 'loan': str,
 'contact': str,
 'day': numpy.int64,
 'month': str,
 'duration': numpy.float64,
 'campaign': numpy.int64,
 'pdays': numpy.float64,
 'previous': numpy.int64,
 'poutcome': str,
 'deposit': str}

# LabelEncoding

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in range(len(dl)):
    if dl[i]==str:
        data[d[i]]= le.fit_transform(data[d[i]])

In [17]:
data

age  job  marital  education  default  balance  housing  loan  contact  \
0     59    0        1          1        0     2343        1     0        2   
1     56    0        1          1        0       45        0     0        2   
2     41    9        1          1        0     1270        1     0        2   
3     55    7        1          1        0     2476        1     0        2   
4     54    0        1          2        0      184        0     0        2   
..   ...  ...      ...        ...      ...      ...      ...   ...      ...   
603   40    7        1          1        0      473        1     0        0   
604   40    6        2          2        0     1616        0     0        1   
605   38    1        0          1        0     1817        1     0        0   
606   54    5        2          1        0      129        0     1        0   
607   54    9        1          1        0     1938        0     1        0   

     day  month  duration  campaign  pdays  previous  poutcome  deposit  
0      5      2    1042.0         1   -1.0         0         0        0  
1      5      2    1467.0         1   -1.0         0         0        0  
2      5      2    1389.0         1   -1.0         0         0        0  
3      5      2     579.0         1   -1.0         0         0        0  
4      5      2     673.0         2   -1.0         0         0        0  
..   ...    ...       ...       ...    ...       ...       ...      ...  
603   28      0     383.0         3   -1.0         0         0        0  
604   28      0    1009.0         7   -1.0         0         0        0  
605   28      0    1096.0         4   -1.0         0         0        0  
606   28      0     867.0         2   -1.0         0         0        0  
607   28      0     551.0         3   -1.0         0         0        0  

[608 rows x 17 columns]

# Finding dublicate rows

In [18]:
dataarray=data.to_numpy()

In [19]:
dataarray

array([[59.,  0.,  1., ...,  0.,  0.,  0.],
       [56.,  0.,  1., ...,  0.,  0.,  0.],
       [41.,  9.,  1., ...,  0.,  0.,  0.],
       ...,
       [38.,  1.,  0., ...,  0.,  0.,  0.],
       [54.,  5.,  2., ...,  0.,  0.,  0.],
       [54.,  9.,  1., ...,  0.,  0.,  0.]])

In [20]:
dataarray[0]

array([ 5.900e+01,  0.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,
        2.343e+03,  1.000e+00,  0.000e+00,  2.000e+00,  5.000e+00,
        2.000e+00,  1.042e+03,  1.000e+00, -1.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00])

In [21]:
droplist=[]
for k in range(len(dataarray)):
    for j in range(k+1,len(dataarray)):
        if(list(dataarray[k])==list(dataarray[j])):
            droplist.append(j)           

# Removing dublicate data/rows

In [22]:
data

age  job  marital  education  default  balance  housing  loan  contact  \
0     59    0        1          1        0     2343        1     0        2   
1     56    0        1          1        0       45        0     0        2   
2     41    9        1          1        0     1270        1     0        2   
3     55    7        1          1        0     2476        1     0        2   
4     54    0        1          2        0      184        0     0        2   
..   ...  ...      ...        ...      ...      ...      ...   ...      ...   
603   40    7        1          1        0      473        1     0        0   
604   40    6        2          2        0     1616        0     0        1   
605   38    1        0          1        0     1817        1     0        0   
606   54    5        2          1        0      129        0     1        0   
607   54    9        1          1        0     1938        0     1        0   

     day  month  duration  campaign  pdays  previous  poutcome  deposit  
0      5      2    1042.0         1   -1.0         0         0        0  
1      5      2    1467.0         1   -1.0         0         0        0  
2      5      2    1389.0         1   -1.0         0         0        0  
3      5      2     579.0         1   -1.0         0         0        0  
4      5      2     673.0         2   -1.0         0         0        0  
..   ...    ...       ...       ...    ...       ...       ...      ...  
603   28      0     383.0         3   -1.0         0         0        0  
604   28      0    1009.0         7   -1.0         0         0        0  
605   28      0    1096.0         4   -1.0         0         0        0  
606   28      0     867.0         2   -1.0         0         0        0  
607   28      0     551.0         3   -1.0         0         0        0  

[608 rows x 17 columns]

In [23]:
data.drop(index=droplist,inplace=True)

In [24]:
data

age  job  marital  education  default  balance  housing  loan  contact  \
0     59    0        1          1        0     2343        1     0        2   
1     56    0        1          1        0       45        0     0        2   
2     41    9        1          1        0     1270        1     0        2   
3     55    7        1          1        0     2476        1     0        2   
4     54    0        1          2        0      184        0     0        2   
..   ...  ...      ...        ...      ...      ...      ...   ...      ...   
603   40    7        1          1        0      473        1     0        0   
604   40    6        2          2        0     1616        0     0        1   
605   38    1        0          1        0     1817        1     0        0   
606   54    5        2          1        0      129        0     1        0   
607   54    9        1          1        0     1938        0     1        0   

     day  month  duration  campaign  pdays  previous  poutcome  deposit  
0      5      2    1042.0         1   -1.0         0         0        0  
1      5      2    1467.0         1   -1.0         0         0        0  
2      5      2    1389.0         1   -1.0         0         0        0  
3      5      2     579.0         1   -1.0         0         0        0  
4      5      2     673.0         2   -1.0         0         0        0  
..   ...    ...       ...       ...    ...       ...       ...      ...  
603   28      0     383.0         3   -1.0         0         0        0  
604   28      0    1009.0         7   -1.0         0         0        0  
605   28      0    1096.0         4   -1.0         0         0        0  
606   28      0     867.0         2   -1.0         0         0        0  
607   28      0     551.0         3   -1.0         0         0        0  

[605 rows x 17 columns]

In [25]:
droplist

[293, 444, 445]

# onehotencoding

In [28]:
dataarray1=data.to_numpy()

In [29]:
dataarray1[0]

array([ 5.900e+01,  0.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,
        2.343e+03,  1.000e+00,  0.000e+00,  2.000e+00,  5.000e+00,
        2.000e+00,  1.042e+03,  1.000e+00, -1.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00])

In [30]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=[]
index=[]
for i in range(len(dl)):
    if dl[i]==str:
        z.append(one.fit_transform(dataarray1[:,i:i+1]).toarray())
        index.append(i)
dataarray1=np.delete(dataarray1,index,axis=1)

C:\Users\mouni\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\mouni\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you us

In [31]:
dataarray1

array([[ 5.900e+01,  2.343e+03,  5.000e+00, ...,  1.000e+00, -1.000e+00,
         0.000e+00],
       [ 5.600e+01,  4.500e+01,  5.000e+00, ...,  1.000e+00, -1.000e+00,
         0.000e+00],
       [ 4.100e+01,  1.270e+03,  5.000e+00, ...,  1.000e+00, -1.000e+00,
         0.000e+00],
       ...,
       [ 3.800e+01,  1.817e+03,  2.800e+01, ...,  4.000e+00, -1.000e+00,
         0.000e+00],
       [ 5.400e+01,  1.290e+02,  2.800e+01, ...,  2.000e+00, -1.000e+00,
         0.000e+00],
       [ 5.400e+01,  1.938e+03,  2.800e+01, ...,  3.000e+00, -1.000e+00,
         0.000e+00]])

In [32]:
dataarray1[0]

array([ 5.900e+01,  2.343e+03,  5.000e+00,  1.042e+03,  1.000e+00,
       -1.000e+00,  0.000e+00])

In [33]:
for j in range(len(z)):
    dataarray1=np.concatenate((z[j],dataarray1),axis=1)   

In [34]:
dataarray1[0]

array([ 1.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,
        0.000e+00,  0.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,
        0.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,
        1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,
        0.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  5.900e+01,  2.343e+03,
        5.000e+00,  1.042e+03,  1.000e+00, -1.000e+00,  0.000e+00])

# feature scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
dataarray1=sc.fit_transform(dataarray1)

In [36]:
dataarray1[0]

array([ 0.        ,  0.        , -0.82495791, -0.59962535,  1.42302495,
       -0.76948376, -0.14818724,  0.80529582,  0.53082922, -0.53082922,
       -0.70010555,  0.70010555,  0.17003401, -0.17003401, -0.43965201,
        0.87988269, -0.56398829, -0.18490007, -0.4608957 ,  0.99834847,
       -0.69225545,  2.93311688, -0.64564838, -0.23239399, -0.15391122,
       -0.4529672 , -0.18962833, -0.18006446, -0.33790602, -0.10008344,
       -0.41803981, -0.17003401, -0.04068942,  2.10492028,  0.76342353,
       -1.41422218,  0.33047075, -0.71506352,  0.        ,  0.        ])

In [37]:
import numpy as np
np.savetxt("file1.csv",dataarray1,delimiter=",")